### ISSUE TITLE
delete room

### ISSUE THREAD

**Issue by mattfeldman** [mattfeldman/nullchat#114]
At least I think so :) owner should be able to delete a room (and probably all of the messages included) should have some confirmation around it.

**Comment by abhiaiyer91** [comment]
Im going to send you a PR for this. Lets chat about it in a few.

In leaveRoom we can set the Rooms status to trashed. Adding a status to the schema. I guess then youd need a modal to confirm the delete. Let me know what you think, could make an ENUM of different room statuses.
