### ISSUE TITLE
Mobile apps ?

### ISSUE THREAD

**Issue by shtefcs** [mattfeldman/nullchat#162]
I am just wondering is it possible to put null chat into native mobile apps for IOS & Android using Cordova ?

Btw, you created awesome thing dude, tnx for sharing it !

**Comment by mattfeldman** [comment]
The current implementation with Semantic UI would likely not be sufficient.  I would likely use https://github.com/meteoric/meteor-ionic

**Comment by mattfeldman** [comment]
Duplicate of  #58
