### ISSUE TITLE
emojione.com - Open source emoji designed for the web

### ISSUE THREAD

**Issue by shtefcs** [mattfeldman/nullchat#163]
This http://emojione.com looks like awesome project to be integrated with nullchat. It would be great if we can replace standard not pretty emoji with this ones.

What you think @mattfeldman

**Comment by mattfeldman** [comment]
nullchat currently supports these emojis (categorized the same way) http://www.emoji-cheat-sheet.com/

What advantage do you see of emojione? Just the appearance? If there is genuine interest in various emoji sets I suppose that alternate sets can be added, but I don't currently have any current plans to replace the emojis

**Comment by shtefcs** [comment]
its modern, better looking, and ur current one was not working when I was chatting with Jelena, i got square from her.

What i have understand emojione would display same on all devices. Also its easy to be noticed that work is putted in that project and that is good. It was just suggestion, if not take u alot of time.

**Comment by mattfeldman** [comment]
Good to know that it handles some device support for you. Leaving this here: https://atmospherejs.com/qnub/emojione if this get's traction.

**Comment by mattfeldman** [comment]
I've started working on this @shtefcs 
- [x] emoji selector
- [x] emoji rendering
- [ ] autocomplete
- [ ] replace emojis collection
- [ ] configure emojione for svg self-hosted emoji assets

**Comment by shtefcs** [comment]
nice to hear that :+1:
