### ISSUE TITLE
Infinite scroll load breaks on 5th load

### ISSUE THREAD

**Issue by master99x** [mattfeldman/nullchat#173]
Scrolling up to trigger infinite load will break on the 5th load.

Repro:
1. Enter or generate enough messages to permit at least 5 infinite loads
2. refresh the page and ensure a scroll bar is present (take a note of the displayed messages)
3. scroll up to trigger infinite load
4. repeat step 3 four more times

Result:
on the fifth load, all of the messages you loaded with steps 3 and 4 will disappear and you will return to the screen similar to the one in step 2 (the messages seen now will be less than or equal to the ones in step 2 [usually less])

**Comment by mattfeldman** [comment]
Good report thanks @master99x - confirmed repro. I'll investigate...
